### PR TITLE
10720 locations template notifications

### PR DESCRIPTION
**Pull request by shanethmoore**
New locations templating mechanism which allows location campaigns to have templated content swapped out with a geofence label

### CODE REVIEW

**Comment by shanetmoore** [comment]
@Sergio-Mira @dominicmarmionswrve Care to review?

**Comment by dominicmarmionswrve** [comment]
:rocket:

**Comment by Sergio-Mira** [comment]
Has another pr been merged with this work? I can only see changes to dependencies

**Comment by shanethmoore** [comment]
Hey Sergio, https://github.com/Swrve/swrve-sdk/pull/1040

**Comment by shanethmoore** [comment]
No idea why I forgot to merge this

**Pull request merged**
