### PR TITLE
12440 Shutdown short-lived executors

### PR DESCRIPTION
**Pull request by Sergio-Mira**
From:
https://github.com/Swrve/swrve-android-sdk/pull/168

### CODE REVIEW

**Comment by Sergio-Mira** [comment]
@dominicmarmionswrve Could you have a quick look?

**Comment by dominicmarmionswrve** [comment]
Can we put all the shutdownNow's in a finally block? Even if it, the code in the try block is perfectly safe, it's a nice pattern to adapt.

**Comment by dominicmarmionswrve** [comment]
🚀  if finally blocks added.

**Comment by Sergio-Mira** [comment]
Moved to finally block, merging

**Comment by dominicmarmionswrve** [comment]
Btw, you can do try/finally blocks without the "catch", which is what I meant.

**Comment by Sergio-Mira** [comment]
Cool! Modified in 4.4

**Pull request merged**
