### PR TITLE
<b> and <i> CSS fixes for conversations

### PR DESCRIPTION
**Pull request by shanetmoore**
Fixed issue where b and i tag styles were not being respected by the phones css which was overwriting styles

### CODE REVIEW

**Comment by shanetmoore** [comment]
@Sergio-Mira @dominicmarmionswrve

**Comment by shanetmoore** [comment]
Worth noting that we won't merge this immediately after approval. I'll need to release the common lib, followed by tweaking the google and core and publishing them too.

**Comment by shanetmoore** [comment]
@dominicmarmionswrve @oisin

**Comment by shanetmoore** [comment]
@davemswrve

**Comment by davemswrve** [comment]
:+1: :rabbit: booya

**Pull request merged**
