### PR TITLE
Location sdk version checks

### PR DESCRIPTION
**Pull request by dominicmarmionswrve**
https://swrvedev.jira.com/browse/SWRVE-12495

@seaders @Sergio-Mira please

### CODE REVIEW

**Comment by Sergio-Mira** [comment]
We don't log a user property with the Location SDK version?

**Comment by dominicmarmionswrve** [comment]
We log it from the location SwrvePlot class

**Comment by dominicmarmionswrve** [comment]
https://github.com/Swrve/swrve-sdk/pull/1232/files#diff-0f87cb832cf8ad07061f8372c3c6701aL42

**Comment by Sergio-Mira** [comment]
🚀 !

**Pull request merged**
